### get a page comments
POST http://127.0.0.1:8000/comments/?action=get HTTP/1.1
content-type: application/json
Accept: application/json

{
    "slug": "test"
}
### create new message
# userid will need to be replaced with jwt header
POST http://127.0.0.1:8000/comments/?action=submit HTTP/1.1
content-type: application/json
Accept: application/json

{
    "userId": "xxx",
    "slug": "testa",
    "body": "test comment"
}
### create new comment as guest
POST http://127.0.0.1:8000/comments/?action=submit HTTP/1.1
content-type: application/json
Accept: application/json

{
    "guest": true,
    "slug": "testa",
    "body": "test comment"
}
### delete message
POST http://127.0.0.1:8000/comments/?action=del HTTP/1.1
content-type: application/json
Accept: application/json

{
    "userId": "xxx",
    "id": "xxx"
}

### mod message
POST http://127.0.0.1:8000/comments/?action=mod HTTP/1.1
content-type: application/json
Accept: application/json

{
    "userId": "xxx",
    "id": "xxx",
    "body": "test comment25a"
}