### register user
POST http://127.0.0.1:8000/users/?action=register HTTP/1.1
content-type: application/json
Accept: application/json

{
    "displayName": "test user",
    "password": "2Message!",
    "email": "test3@me.com"
}
### login user to get jwt
POST http://127.0.0.1:8000/users/?action=login HTTP/1.1
content-type: application/json
Accept: application/json

{
    "password": "2Manytests!",
    "email": "test@me.com"
}
### sso facebook google?
GET http://127.0.0.1:8000/users/?action=profile HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json
Accept: application/json

###