name: unit tests

# use https://marketplace.visualstudio.com/items?itemName=me-dutour-mathieu.vscode-github-actions to validate yml in vscode
env:
  DOCKER_DRIVER: overlay
  rIds: ${{ secrets.rIds }}
  phpVersion: 7.1

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2

  #     - uses: php-actions/composer@v5

  #     - name: PHPUnit Tests
  #       uses: php-actions/phpunit@v2
  #       env:
  #         TEST_NAME: Scarlett
  #       with:
  #         bootstrap: vendor/autoload.php
  #         configuration: test/phpunit.xml
  #         args: --coverage-text


  unit_test_db_mysql:
    runs-on: ubuntu-latest
    # Service containers to run with `runner-job`
    services:
      # Label used to access the service container
      localhost_mysql:
        # Docker Hub image
        image: mysql:5.7.29
        #
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: "testcomments"
          MYSQL_ROOT_PASSWORD: "mysecretpw"
    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4.9'
          tools: composer:v2

      - name: composer
        run: composer install

      - name: enabledb
        run: |
          cp ./config/connections-github.php ./config/connections.php
          cp library/mailFunctions-sendGrid.php library/mailFunctions.php
          php ./tests/initialize.php

      - name: run tests
        run: vendor/bin/phpunit   

      # - uses: php-actions/composer@v5

      # - name: PHPUnit Tests
      #   uses: php-actions/phpunit@v2
      #   env:
      #     TEST_NAME: Scarlett
      #   with:
      #     bootstrap: vendor/autoload.php
      #     configuration: phpunit.xml
      # php_version 
      #     args: --coverage-text